INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-01-14', N'Makarsankranti')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-02-05', N'Vasantpanchami')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-03-01', N'Mahashivratri')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-03-17', N'Holika Dahan')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-03-18', N'Holi')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-03-22', N'New Year')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-04-10', N'Hanuman Jayanti')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-04-10', N'Ramnavami')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-05-03', N'Akshay Tritya')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-05-30', N'Savitri Pooja')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-07-01', N'Puri Rath Yatra')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-07-13', N'Guru Purnima')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-08-02', N'Naag Panchami')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-08-11', N'Raksha Bandhan')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-08-19', N'Krishna Janmasthami')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-08-31', N'Ganesh Chaturthi')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-09-26', N'Navratri begins')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-10-04', N'Navratri ends')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-10-05', N'Dussehra')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-10-09', N'Sharad Poornima')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-10-13', N'Karwa Chauth')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-10-22', N'Dhanteras')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-10-24', N'Diwali')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-10-26', N'Bhai Dooj')
INSERT INTO [dbo].[calendar] ([date], [occassion]) VALUES (N'2022-10-30', N'Chhath Pooja')
